services:
  bastion:
    image: ubuntu:20.04
    container_name: bastion
    networks:
      bastion_net:
        ipv4_address: 192.168.1.2
    command: ["sleep", "infinity"]
    tty: true
    stdin_open: true
    volumes:
      - ./bastion:/data  # 挂载主机文件夹，方便调试

  instance01:
    image: ./instance01
    container_name: instance01
    networks:
      bastion_net:
        ipv4_address: 192.168.1.10
    command: ["sleep", "infinity"]
    tty: true
    stdin_open: true
    volumes:
      - ./instance01:/data

  instance02:
    image: ./instance02
    container_name: instance02
    networks:
      bastion_net:
        ipv4_address: 192.168.1.11
    command: ["sleep", "infinity"]  
    tty: true
    stdin_open: true
    volumes:
      - ./instance02:/data

networks:
  bastion_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
