- name: Main Playbook
  hosts: localhost
  vars:
    region: "ap-northeast-2"
    repo_name: "codera/auth_image"
    tag: "latest"
    output_file: "/tmp/auth_image.tar"
  tasks:
    - name: Ensure jq is installed
      ansible.builtin.package:
        name: jq
        state: present
      when: ansible_os_family in ["Debian", "RedHat"]

    - name: Download image layers from ECR
      include_tasks: ecr_download.yml
      vars:
        repository_name: "{{ repo_name }}"
        image_tag: "{{ tag }}"
        tarball_path: "{{ output_file }}"
        aws_region: "{{ region }}"

    - name: Deploy to auth instances
      include_tasks: auth_instances.yml
      vars:
        image_tarball: "{{ output_file }}"

    - name: Deploy to API instances
      include_tasks: api_instances.yml
      vars:
        image_tarball: "{{ output_file }}"
